Create contributing.md
soham0005/ElectroKart pull request #27
Opened 2024-10-03 10:12 UTC by rajatsinghal02

i have created the contributing.md file.

2024-10-03 10:27 UTC, rajatsinghal02 commented
@soham0005 please check the contributing.md file i have added to the repo

2024-10-03 17:26 UTC, PayalKumari10 commented
Hello @rajatsinghal02 I wanted to share a few suggestions to help improve our CONTRIBUTING.md file and enhance the contribution process. Here are some points to consider:

1.  **Duplicate Content:**

It would be great to remove the repeated section starting from <h1 align="center">Contributors Guide for ElectroKart⚡</h1> to keep the document concise.

2.  **Branch Naming:**

For clarity, I suggest using branch names like feature/<feature_name> or fix/<issue_name>. This will help everyone understand the purpose of the branches at a glance.

3. **Commit Messages:**

It might be helpful to encourage the use of descriptive commit messages. For example:    **_git commit -m "feat: added new feature"_**

4.**Prerequisites Section:**

Including a section that lists the required tools (like Node.js and npm versions) could be beneficial for new contributors.

5.**Testing:**

A friendly reminder to run tests before pushing changes would ensure our code stays robust:  **_npm run test_**

6. **Issue Tracker:**

It might be useful to ask contributors to assign an issue to themselves before they start working on it. This helps keep track of progress.


7. **PR Descriptions:**

Suggesting that contributors include detailed PR descriptions, especially with screenshots for UI changes, could enhance our review process.

8. **Fix Commit Block:**

Lastly, we should consider removing the **css** block around the commit step and instead use a **bash** block for better clarity.



Thank you all for your hard work and contributions! If you have any questions or thoughts about these suggestions, feel free to reach out. 😊

2024-10-03 17:31 UTC, rajatsinghal02 commented
@PayalKumari10 I have updated all these in a while.

2024-10-03 17:52 UTC, PayalKumari10 commented
> @PayalKumari10 I have updated all these in a while.

Hey @rajatsinghal02 ,

Could you please review the points I shared earlier? Some of them are important to add, while others need correcting in the file. Once these updates are made, I’ll go ahead and merge them into the repository.

Thanks so much for your effort!

2024-10-03 18:00 UTC, PayalKumari10 requested changes

2024-10-03 18:00 UTC, PayalKumari10 commented on contributing.md
> +git commit -m "Added new feature/fixed bug."
this line

2024-10-03 18:57 UTC, PayalKumari10 requested changes

2024-10-03 18:57 UTC, PayalKumari10 commented on contributing.md
> +6. Always ensure all tests pass before pushing your changes.
great job  @rajatsinghal02 , on the updates! Please add “Always ensure all tests pass before pushing your changes by running: npm run test” to enhance clarity for new contributors. Thank you!

2024-10-03 19:16 UTC, PayalKumari10 commented
> @PayalKumari10 File Updated

Hello @rajatsinghal02 , Thank you for solving and updating the issues! Great job! Happy coding, and we look forward to you tackling more challenges with us!

2024-10-03 19:17 UTC, PayalKumari10 commented
Hi @soham0005 , I have reviewed the changes, and everything looks good.  Could you please merge this PR? 
Thank you! 
Best,
@PayalKumari10

2024-10-03 20:27 UTC, soham0005 commented
@rajatsinghal02 please do make the necessary changes to pass all the test cases!

2024-10-04 14:18 UTC, PRathod27 approved these changes

2024-10-04 14:45 UTC, soham0005 approved these changes

2024-10-04 15:57 UTC, merged